/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin/_authenticated'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CheckoutCallbackRouteImport } from './routes/checkout/callback'
import { Route as OrderPublicTokenRouteImport } from './routes/order/$publicToken'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopProductSlugRouteImport } from './routes/shop/$productSlug'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin/_authenticated/index'
import { Route as AdminAuthenticatedCategoriesRouteImport } from './routes/admin/_authenticated/categories'
import { Route as AdminAuthenticatedOrdersRouteImport } from './routes/admin/_authenticated/orders'
import { Route as AdminAuthenticatedProductsRouteImport } from './routes/admin/_authenticated/products'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWebhooksPaystackRouteImport } from './routes/api/webhooks/paystack'
import { Route as AdminAuthenticatedCategoriesIndexRouteImport } from './routes/admin/_authenticated/categories/index'
import { Route as AdminAuthenticatedOrdersIndexRouteImport } from './routes/admin/_authenticated/orders/index'
import { Route as AdminAuthenticatedOrdersOrderIdRouteImport } from './routes/admin/_authenticated/orders/$orderId'
import { Route as AdminAuthenticatedProductsIndexRouteImport } from './routes/admin/_authenticated/products/index'
import { Route as AdminAuthenticatedProductsProductIdRouteImport } from './routes/admin/_authenticated/products/$productId'
import { Route as AdminAuthenticatedProductsNewRouteImport } from './routes/admin/_authenticated/products/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutCallbackRoute = CheckoutCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => CheckoutRoute,
} as any)
const OrderPublicTokenRoute = OrderPublicTokenRouteImport.update({
  id: '/order/$publicToken',
  path: '/order/$publicToken',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductSlugRoute = ShopProductSlugRouteImport.update({
  id: '/shop/$productSlug',
  path: '/shop/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedCategoriesRoute =
  AdminAuthenticatedCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedOrdersRoute =
  AdminAuthenticatedOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedProductsRoute =
  AdminAuthenticatedProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaystackRoute = ApiWebhooksPaystackRouteImport.update({
  id: '/api/webhooks/paystack',
  path: '/api/webhooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedCategoriesIndexRoute =
  AdminAuthenticatedCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAuthenticatedCategoriesRoute,
  } as any)
const AdminAuthenticatedOrdersIndexRoute =
  AdminAuthenticatedOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAuthenticatedOrdersRoute,
  } as any)
const AdminAuthenticatedOrdersOrderIdRoute =
  AdminAuthenticatedOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AdminAuthenticatedOrdersRoute,
  } as any)
const AdminAuthenticatedProductsIndexRoute =
  AdminAuthenticatedProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAuthenticatedProductsRoute,
  } as any)
const AdminAuthenticatedProductsProductIdRoute =
  AdminAuthenticatedProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AdminAuthenticatedProductsRoute,
  } as any)
const AdminAuthenticatedProductsNewRoute =
  AdminAuthenticatedProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAuthenticatedProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/order/$publicToken': typeof OrderPublicTokenRoute
  '/shop/$productSlug': typeof ShopProductSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/categories': typeof AdminAuthenticatedCategoriesRouteWithChildren
  '/admin/orders': typeof AdminAuthenticatedOrdersRouteWithChildren
  '/admin/products': typeof AdminAuthenticatedProductsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
  '/admin/orders/$orderId': typeof AdminAuthenticatedOrdersOrderIdRoute
  '/admin/products/$productId': typeof AdminAuthenticatedProductsProductIdRoute
  '/admin/products/new': typeof AdminAuthenticatedProductsNewRoute
  '/admin/categories/': typeof AdminAuthenticatedCategoriesIndexRoute
  '/admin/orders/': typeof AdminAuthenticatedOrdersIndexRoute
  '/admin/products/': typeof AdminAuthenticatedProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
  '/cart': typeof CartRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/order/$publicToken': typeof OrderPublicTokenRoute
  '/shop/$productSlug': typeof ShopProductSlugRoute
  '/checkout': typeof CheckoutIndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/admin/orders/$orderId': typeof AdminAuthenticatedOrdersOrderIdRoute
  '/admin/products/$productId': typeof AdminAuthenticatedProductsProductIdRoute
  '/admin/products/new': typeof AdminAuthenticatedProductsNewRoute
  '/admin/categories': typeof AdminAuthenticatedCategoriesIndexRoute
  '/admin/orders': typeof AdminAuthenticatedOrdersIndexRoute
  '/admin/products': typeof AdminAuthenticatedProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/order/$publicToken': typeof OrderPublicTokenRoute
  '/shop/$productSlug': typeof ShopProductSlugRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/_authenticated/categories': typeof AdminAuthenticatedCategoriesRouteWithChildren
  '/admin/_authenticated/orders': typeof AdminAuthenticatedOrdersRouteWithChildren
  '/admin/_authenticated/products': typeof AdminAuthenticatedProductsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/paystack': typeof ApiWebhooksPaystackRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
  '/admin/_authenticated/orders/$orderId': typeof AdminAuthenticatedOrdersOrderIdRoute
  '/admin/_authenticated/products/$productId': typeof AdminAuthenticatedProductsProductIdRoute
  '/admin/_authenticated/products/new': typeof AdminAuthenticatedProductsNewRoute
  '/admin/_authenticated/categories/': typeof AdminAuthenticatedCategoriesIndexRoute
  '/admin/_authenticated/orders/': typeof AdminAuthenticatedOrdersIndexRoute
  '/admin/_authenticated/products/': typeof AdminAuthenticatedProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/admin/login'
    | '/checkout/callback'
    | '/order/$publicToken'
    | '/shop/$productSlug'
    | '/checkout/'
    | '/shop/'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/api/auth/$'
    | '/api/webhooks/paystack'
    | '/admin/'
    | '/admin/orders/$orderId'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/categories/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/admin/login'
    | '/checkout/callback'
    | '/order/$publicToken'
    | '/shop/$productSlug'
    | '/checkout'
    | '/shop'
    | '/api/auth/$'
    | '/api/webhooks/paystack'
    | '/admin/orders/$orderId'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/checkout/callback'
    | '/order/$publicToken'
    | '/shop/$productSlug'
    | '/checkout/'
    | '/shop/'
    | '/admin/_authenticated/categories'
    | '/admin/_authenticated/orders'
    | '/admin/_authenticated/products'
    | '/api/auth/$'
    | '/api/webhooks/paystack'
    | '/admin/_authenticated/'
    | '/admin/_authenticated/orders/$orderId'
    | '/admin/_authenticated/products/$productId'
    | '/admin/_authenticated/products/new'
    | '/admin/_authenticated/categories/'
    | '/admin/_authenticated/orders/'
    | '/admin/_authenticated/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  OrderPublicTokenRoute: typeof OrderPublicTokenRoute
  ShopProductSlugRoute: typeof ShopProductSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksPaystackRoute: typeof ApiWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/callback': {
      id: '/checkout/callback'
      path: '/callback'
      fullPath: '/checkout/callback'
      preLoaderRoute: typeof CheckoutCallbackRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/order/$publicToken': {
      id: '/order/$publicToken'
      path: '/order/$publicToken'
      fullPath: '/order/$publicToken'
      preLoaderRoute: typeof OrderPublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productSlug': {
      id: '/shop/$productSlug'
      path: '/shop/$productSlug'
      fullPath: '/shop/$productSlug'
      preLoaderRoute: typeof ShopProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/categories': {
      id: '/admin/_authenticated/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAuthenticatedCategoriesRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/orders': {
      id: '/admin/_authenticated/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAuthenticatedOrdersRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/products': {
      id: '/admin/_authenticated/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAuthenticatedProductsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paystack': {
      id: '/api/webhooks/paystack'
      path: '/api/webhooks/paystack'
      fullPath: '/api/webhooks/paystack'
      preLoaderRoute: typeof ApiWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated/categories/': {
      id: '/admin/_authenticated/categories/'
      path: '/'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminAuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AdminAuthenticatedCategoriesRoute
    }
    '/admin/_authenticated/orders/': {
      id: '/admin/_authenticated/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminAuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AdminAuthenticatedOrdersRoute
    }
    '/admin/_authenticated/orders/$orderId': {
      id: '/admin/_authenticated/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminAuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AdminAuthenticatedOrdersRoute
    }
    '/admin/_authenticated/products/': {
      id: '/admin/_authenticated/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminAuthenticatedProductsIndexRouteImport
      parentRoute: typeof AdminAuthenticatedProductsRoute
    }
    '/admin/_authenticated/products/$productId': {
      id: '/admin/_authenticated/products/$productId'
      path: '/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminAuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AdminAuthenticatedProductsRoute
    }
    '/admin/_authenticated/products/new': {
      id: '/admin/_authenticated/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminAuthenticatedProductsNewRouteImport
      parentRoute: typeof AdminAuthenticatedProductsRoute
    }
  }
}

interface AdminAuthenticatedCategoriesRouteChildren {
  AdminAuthenticatedCategoriesIndexRoute: typeof AdminAuthenticatedCategoriesIndexRoute
}

const AdminAuthenticatedCategoriesRouteChildren: AdminAuthenticatedCategoriesRouteChildren =
  {
    AdminAuthenticatedCategoriesIndexRoute:
      AdminAuthenticatedCategoriesIndexRoute,
  }

const AdminAuthenticatedCategoriesRouteWithChildren =
  AdminAuthenticatedCategoriesRoute._addFileChildren(
    AdminAuthenticatedCategoriesRouteChildren,
  )

interface AdminAuthenticatedOrdersRouteChildren {
  AdminAuthenticatedOrdersOrderIdRoute: typeof AdminAuthenticatedOrdersOrderIdRoute
  AdminAuthenticatedOrdersIndexRoute: typeof AdminAuthenticatedOrdersIndexRoute
}

const AdminAuthenticatedOrdersRouteChildren: AdminAuthenticatedOrdersRouteChildren =
  {
    AdminAuthenticatedOrdersOrderIdRoute: AdminAuthenticatedOrdersOrderIdRoute,
    AdminAuthenticatedOrdersIndexRoute: AdminAuthenticatedOrdersIndexRoute,
  }

const AdminAuthenticatedOrdersRouteWithChildren =
  AdminAuthenticatedOrdersRoute._addFileChildren(
    AdminAuthenticatedOrdersRouteChildren,
  )

interface AdminAuthenticatedProductsRouteChildren {
  AdminAuthenticatedProductsProductIdRoute: typeof AdminAuthenticatedProductsProductIdRoute
  AdminAuthenticatedProductsNewRoute: typeof AdminAuthenticatedProductsNewRoute
  AdminAuthenticatedProductsIndexRoute: typeof AdminAuthenticatedProductsIndexRoute
}

const AdminAuthenticatedProductsRouteChildren: AdminAuthenticatedProductsRouteChildren =
  {
    AdminAuthenticatedProductsProductIdRoute:
      AdminAuthenticatedProductsProductIdRoute,
    AdminAuthenticatedProductsNewRoute: AdminAuthenticatedProductsNewRoute,
    AdminAuthenticatedProductsIndexRoute: AdminAuthenticatedProductsIndexRoute,
  }

const AdminAuthenticatedProductsRouteWithChildren =
  AdminAuthenticatedProductsRoute._addFileChildren(
    AdminAuthenticatedProductsRouteChildren,
  )

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedCategoriesRoute: typeof AdminAuthenticatedCategoriesRouteWithChildren
  AdminAuthenticatedOrdersRoute: typeof AdminAuthenticatedOrdersRouteWithChildren
  AdminAuthenticatedProductsRoute: typeof AdminAuthenticatedProductsRouteWithChildren
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedCategoriesRoute:
    AdminAuthenticatedCategoriesRouteWithChildren,
  AdminAuthenticatedOrdersRoute: AdminAuthenticatedOrdersRouteWithChildren,
  AdminAuthenticatedProductsRoute: AdminAuthenticatedProductsRouteWithChildren,
  AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

interface AdminRouteChildren {
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutCallbackRoute: typeof CheckoutCallbackRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCallbackRoute: CheckoutCallbackRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  OrderPublicTokenRoute: OrderPublicTokenRoute,
  ShopProductSlugRoute: ShopProductSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksPaystackRoute: ApiWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
